remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Kancio
description: Beli pulsa murah dan lengkap
show_downloads: true
github:
  zip_url: https://play.google.com/store/apps/details?id=com.kancio.indonesia&hl=in&gl=US
  another_url: https://play.google.com/store/apps/details?id=com.kancio.indonesia&hl=in&gl=US
